language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "nightly" # currently points to 3.6-dev

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=pickems.settings
  - export PYTHONPATH=$HOME/builds/kcin1018/pickems-py
  - export PIP_USE_MIRRORS=true

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

# command to run tests
script: manage.py test
