# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 10:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'api', '0001_initial'), (b'api', '0002_auto_20160714_1056'), (b'api', '0003_auto_20160721_1055')]

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickemsUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NflGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('starts_at', models.DateTimeField()),
                ('game_key', models.CharField(max_length=10, unique=True)),
                ('game_id', models.CharField(max_length=15, unique=True)),
                ('type', models.CharField(choices=[(b'REG', b'REG'), (b'POST', b'POST')], default=b'REG', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='NflPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsis_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NflStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('td', models.IntegerField(default=0)),
                ('fg', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('two', models.IntegerField(default=0)),
                ('diff', models.IntegerField(default=0)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.NflPlayer')),
            ],
        ),
        migrations.CreateModel(
            name='NflTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=5, unique=True)),
                ('conference', models.CharField(choices=[(b'AFC', b'AFC'), (b'NFC', b'NFC')], max_length=5)),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Storyline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('story', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PickemsUser')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('number', models.IntegerField()),
                ('playmaker', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('picked_at', models.DateTimeField()),
                ('pick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.NflStat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='api.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayoffPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_points', models.IntegerField()),
                ('picks', models.TextField()),
                ('valid', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('picked_at', models.DateTimeField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playoff_picks', to='api.Team')),
            ],
        ),
        migrations.AddField(
            model_name='nflstat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.NflTeam', to_field=b'abbr'),
        ),
        migrations.AddField(
            model_name='nflplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.NflTeam', to_field=b'abbr'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_away', to='api.NflTeam', to_field=b'abbr'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_home', to='api.NflTeam', to_field=b'abbr'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='losing_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_lost', to='api.NflTeam', to_field=b'abbr'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_won', to='api.NflTeam', to_field=b'abbr'),
        ),
        migrations.AlterUniqueTogether(
            name='teampick',
            unique_together=set([('team', 'week', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='nflplayer',
            unique_together=set([('gsis_id', 'active')]),
        ),
        migrations.AlterField(
            model_name='nflstat',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.NflPlayer'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.PickemsUser'),
        ),
    ]
