# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teamwinloss'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField()),
                ('playoff', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='api.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='teamwinloss',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wl', to='api.Team'),
        ),
    ]
