# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160813_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrankings',
            name='category',
            field=models.CharField(default=b'bronze', max_length=10),
        ),
    ]
