# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teamrankings_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekLeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('points', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly', to='api.Team')),
            ],
        ),
    ]
