# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_weekleaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPossible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('pick1_points', models.IntegerField()),
                ('pick1_playmaker', models.BooleanField()),
                ('pick2_points', models.IntegerField()),
                ('pick2_playmaker', models.BooleanField()),
                ('total', models.IntegerField()),
                ('pick1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best1', to='api.NflStat')),
                ('pick2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best2', to='api.NflStat')),
            ],
        ),
    ]
